### ISSUE TITLE
Error creating Db-connected services: tables with "_"

### ISSUE THREAD

**Issue by wesleywillians** [zfcampus/zf-apigility-admin-ui#78]
When I try to create a new db-connected rest service using a table with "_"(underscore), I get this error message:

"Error saving field".

I can see the files are generated, but Apigility UI cannot fetch the service.

I tried using:
"zfcampus/zf-apigility-admin-ui": "dev-develop",

If I use only apigility 1.3.1, there is still the JS bug during the service creation (#PR75), so I changed to dev-develop.

Any idea?

**Comment by gartner** [comment]
Been digging a bit in this, as I also ran into this.

It seems that when the new service is created, if the table name contains an underscore ( _ ), the API will convert this to what looks like CamelCase.

But when the UI then wants to create the fields for this newly created service, it (the UI) will still use the tablename with the underscore in it, when accessing the api (/apigility/api/module/<apiname>/rest/<apiname>-<api-version>-Rest-<Table_name>-Controller/input-filter)

But the API will this time expect the controller-part being specified with the tablename camedcased:
(/apigility/api/module/<apiname>/rest/<apiname>-<api-version>-Rest-<TableName>-Controller/input-filter)

But I do not know if this should be fixed in the UI-code or in the API-code ?

**Comment by alessandrogarcez** [comment]
Hi Wesley, I got the same error.
http://stackoverflow.com/questions/32011684/apigility-error-saving-field-while-creating-db-connected-service?noredirect=1#comment51978970_32011684
I have no idea yet... but I'm looking for a solution.

**Comment by alessandrogarcez** [comment]
Hello @gartner and @wesleywillians ... I found a solution.
In zfcampus-apigility-admin-ui change the function capitalizeFirstLetter in file src/apigility-ui/service/api.service.js adding the line "string = string.replace(/_(\w)/g, function(_,letter) { return letter.toUpperCase(); });" before the return.

I found a issue where were applied the solution but it seems not be in currently code... I don't know why. 
https://github.com/zfcampus/zf-apigility-admin-ui/pull/59/files

I'm using "zfcampus/zf-apigility-admin-ui": "dev-develop".

**Comment by alessandrogarcez** [comment]
It had already been fixed but it was undone in commit https://github.com/zfcampus/zf-apigility-admin-ui/commit/0cbaf331c6cebf9652b45619f0025f7ddbebeee2 . 

@weierophinney can you tale a look because a bug was reopen in your commit?

**Comment by weierophinney** [comment]
I have no idea why that was removed, tbh; my guess is that I may have been working from an older commit when applying a patch. I'll get that updated shortly.

**Comment by ezimuel** [comment]
I fixed this issue with PR #83.

**Comment by leonardo-piseri** [comment]
This issue is still open, and fix in capitalizeFirstLetter() function has been removed (can't guess why).
Can you change to status "open"?

**Comment by colinkelly** [comment]
Yes @leonardo-piseri, you are right. The fix #59  for this issue has been overwritten and this is why I have made a new pull request for that #100. We'll just have to wait for the next version to be updated.

**Comment by MihaiTudorP** [comment]
Hi. Even after the fixes mentioned earlier, I am still encountering the errors.
The automatic discovery does not work for Oracle database (I am getting ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA in /opt/apigw/apigility/vendor/zendframework/zend-db/src/Adapter/Driver/Oci8/Connection.php on line 122).
After hardcoding the credentials, I see the tables. However, when attempting to create db-connected services, I am getting "Error saving field". When I attempt to access them, I am getting "Unable to fetch service". I am currently stuck with this and I don't know what to do to solve the problem.
Any ideas?

**Comment by impactcolor** [comment]
This says closed but I am also having same issue.  Any updates?

**Comment by strausmann** [comment]
Hello, i have the same error. I use Apigility 1.3.2
